// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqpb9ALnpq5pep_P3hQ8Pn7vtZinoSTs',
    appId: '1:431550521264:web:44ba2b6b96358983874075',
    messagingSenderId: '431550521264',
    projectId: 'farmbridge-ac380',
    authDomain: 'farmbridge-ac380.firebaseapp.com',
    storageBucket: 'farmbridge-ac380.firebasestorage.app',
    measurementId: 'G-4333L7GRN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc5-M6nYGl_vqANL2aD3c8MT0BAL2oVbc',
    appId: '1:431550521264:android:25c22e9f3b8b554c874075',
    messagingSenderId: '431550521264',
    projectId: 'farmbridge-ac380',
    storageBucket: 'farmbridge-ac380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaU3Y5AOCVo9I7nLLT6RMnd1_3l4i4Yk8',
    appId: '1:431550521264:ios:8ef3ee6e607888db874075',
    messagingSenderId: '431550521264',
    projectId: 'farmbridge-ac380',
    storageBucket: 'farmbridge-ac380.firebasestorage.app',
    iosClientId: '431550521264-9unkk1k352cah9ndd6h5q2d6ngangkhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaU3Y5AOCVo9I7nLLT6RMnd1_3l4i4Yk8',
    appId: '1:431550521264:ios:8ef3ee6e607888db874075',
    messagingSenderId: '431550521264',
    projectId: 'farmbridge-ac380',
    storageBucket: 'farmbridge-ac380.firebasestorage.app',
    iosClientId: '431550521264-9unkk1k352cah9ndd6h5q2d6ngangkhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeqpb9ALnpq5pep_P3hQ8Pn7vtZinoSTs',
    appId: '1:431550521264:web:d34cb466925224a2874075',
    messagingSenderId: '431550521264',
    projectId: 'farmbridge-ac380',
    authDomain: 'farmbridge-ac380.firebaseapp.com',
    storageBucket: 'farmbridge-ac380.firebasestorage.app',
    measurementId: 'G-LCKPVJV8PM',
  );
}
